export const GET_AUTHOR_REQUEST = 'GET_AUTHOR_REQUEST';
export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';
export const GET_AUTHOR_FAILED = 'GET_AUTHOR_FAILED';

export const GET_FORMATIONS_REQUEST = 'GET_FORMATIONS_REQUEST';
export const GET_FORMATIONS_SUCCESS = 'GET_FORMATIONS_SUCCESS';
export const GET_FORMATIONS_FAILED = 'GET_FORMATIONS_FAILED';

export const GET_DATA_FORMATION = 'GET_DATA_FORMATION';
export const GET_DATA_XP = 'GET_DATA_XP';

// * Gestion langue du portfolio
export const SET_LANG = 'SET_LANG';
