export const GET_AUTHOR_REQUEST = 'GET_AUTHOR_REQUEST';
export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';
export const GET_AUTHOR_FAILED = 'GET_AUTHOR_FAILED';

export const GET_FORMATIONS_REQUEST = 'GET_FORMATIONS_REQUEST';
export const GET_FORMATIONS_SUCCESS = 'GET_FORMATIONS_SUCCESS';
export const GET_FORMATIONS_FAILED = 'GET_FORMATIONS_FAILED';

export const GET_FORMATION_REQUEST = 'GET_FORMATION_REQUEST';
export const GET_FORMATION_SUCCESS = 'GET_FORMATION_SUCCESS';
export const GET_FORMATION_FAILED = 'GET_FORMATION_FAILED';

export const GET_SKILLS_REQUEST = 'GET_SKILLS_REQUEST';
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS';
export const GET_SKILLS_FAILED = 'GET_SKILLS_FAILED';

export const GET_XP_REQUEST = 'GET_XP_REQUEST';
export const GET_XP_SUCCESS = 'GET_XP_SUCCESS';
export const GET_XP_FAILED = 'GET_XP_FAILED';

export const GET_DATA_FORMATION = 'GET_DATA_FORMATION';
export const GET_DATA_XP = 'GET_DATA_XP';

// * Gestion langue du portfolio
export const SET_LANG = 'SET_LANG';
